// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs SET
  status = 'claimed',
  claimed_by = $1,
  claimed_at = now(),
  heartbeat_at = now(),
  updated_at = now()
WHERE id = (
  SELECT id FROM jobs
  WHERE status = 'pending' AND run_after <= now() AND cancel_requested = false
  ORDER BY created_at
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, video_id, type, status, attempts, max_attempts, run_after, claimed_by, claimed_at, heartbeat_at, payload, last_error, cancel_requested, created_at, updated_at
`

// ClaimJob must stay a SINGLE statement: SELECT … FOR UPDATE SKIP LOCKED
// inside the UPDATE subquery is what makes concurrent claims safe (D-02).
func (q *Queries) ClaimJob(ctx context.Context, claimedBy pgtype.Text) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, claimedBy)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Type,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.Payload,
		&i.LastError,
		&i.CancelRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :one
UPDATE jobs SET status = 'completed', updated_at = now()
WHERE id = $1 AND status = 'claimed' AND claimed_by = $2
RETURNING id, video_id, type, status, attempts, max_attempts, run_after, claimed_by, claimed_at, heartbeat_at, payload, last_error, cancel_requested, created_at, updated_at
`

type CompleteJobParams struct {
	ID        uuid.UUID   `json:"id"`
	ClaimedBy pgtype.Text `json:"claimed_by"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, completeJob, arg.ID, arg.ClaimedBy)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Type,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.Payload,
		&i.LastError,
		&i.CancelRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (video_id, type, payload)
VALUES ($1, $2, $3)
RETURNING id, video_id, type, status, attempts, max_attempts, run_after, claimed_by, claimed_at, heartbeat_at, payload, last_error, cancel_requested, created_at, updated_at
`

type EnqueueJobParams struct {
	VideoID uuid.UUID `json:"video_id"`
	Type    string    `json:"type"`
	Payload []byte    `json:"payload"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, enqueueJob, arg.VideoID, arg.Type, arg.Payload)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Type,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.Payload,
		&i.LastError,
		&i.CancelRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :one
UPDATE jobs SET
  attempts = attempts + 1,
  status = CASE WHEN attempts + 1 < max_attempts THEN 'pending' ELSE 'failed' END,
  run_after = CASE
    WHEN attempts + 1 < max_attempts
    THEN now() + power(2, attempts + 1) * interval '30 seconds'
    ELSE run_after END,
  last_error = $3,
  claimed_by = NULL,
  claimed_at = NULL,
  heartbeat_at = NULL,
  updated_at = now()
WHERE id = $1 AND status = 'claimed' AND claimed_by = $2
RETURNING id, video_id, type, status, attempts, max_attempts, run_after, claimed_by, claimed_at, heartbeat_at, payload, last_error, cancel_requested, created_at, updated_at
`

type FailJobParams struct {
	ID        uuid.UUID   `json:"id"`
	ClaimedBy pgtype.Text `json:"claimed_by"`
	LastError pgtype.Text `json:"last_error"`
}

// FailJob increments attempts; below max_attempts the job returns to pending
// with exponential backoff (2^attempts × 30 s), otherwise it settles failed.
func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, failJob, arg.ID, arg.ClaimedBy, arg.LastError)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Type,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.Payload,
		&i.LastError,
		&i.CancelRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, video_id, type, status, attempts, max_attempts, run_after, claimed_by, claimed_at, heartbeat_at, payload, last_error, cancel_requested, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Type,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.Payload,
		&i.LastError,
		&i.CancelRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatJob = `-- name: HeartbeatJob :one
UPDATE jobs SET heartbeat_at = now(), updated_at = now()
WHERE id = $1 AND status = 'claimed' AND claimed_by = $2
RETURNING id, video_id, type, status, attempts, max_attempts, run_after, claimed_by, claimed_at, heartbeat_at, payload, last_error, cancel_requested, created_at, updated_at
`

type HeartbeatJobParams struct {
	ID        uuid.UUID   `json:"id"`
	ClaimedBy pgtype.Text `json:"claimed_by"`
}

func (q *Queries) HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, heartbeatJob, arg.ID, arg.ClaimedBy)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Type,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.Payload,
		&i.LastError,
		&i.CancelRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobsByVideo = `-- name: ListJobsByVideo :many
SELECT id, video_id, type, status, attempts, max_attempts, run_after, claimed_by, claimed_at, heartbeat_at, payload, last_error, cancel_requested, created_at, updated_at FROM jobs WHERE video_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListJobsByVideo(ctx context.Context, videoID uuid.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Type,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAfter,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.HeartbeatAt,
			&i.Payload,
			&i.LastError,
			&i.CancelRequested,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCancelRequested = `-- name: MarkCancelRequested :one
UPDATE jobs SET cancel_requested = true, updated_at = now()
WHERE id = $1 AND status IN ('pending', 'claimed')
RETURNING id, video_id, type, status, attempts, max_attempts, run_after, claimed_by, claimed_at, heartbeat_at, payload, last_error, cancel_requested, created_at, updated_at
`

// Cancel is cooperative: a pending job with cancel_requested is skipped by
// the claim scan; a claimed job sees the flag via GetJob/Heartbeat.
func (q *Queries) MarkCancelRequested(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, markCancelRequested, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Type,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.Payload,
		&i.LastError,
		&i.CancelRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
