// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID              uuid.UUID          `json:"id"`
	VideoID         uuid.UUID          `json:"video_id"`
	Type            string             `json:"type"`
	Status          string             `json:"status"`
	Attempts        int32              `json:"attempts"`
	MaxAttempts     int32              `json:"max_attempts"`
	RunAfter        time.Time          `json:"run_after"`
	ClaimedBy       pgtype.Text        `json:"claimed_by"`
	ClaimedAt       pgtype.Timestamptz `json:"claimed_at"`
	HeartbeatAt     pgtype.Timestamptz `json:"heartbeat_at"`
	Payload         []byte             `json:"payload"`
	LastError       pgtype.Text        `json:"last_error"`
	CancelRequested bool               `json:"cancel_requested"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	ProgressPercent int32              `json:"progress_percent"`
	ProgressStage   string             `json:"progress_stage"`
}

type ReleaseChecklist struct {
	ID        uuid.UUID          `json:"id"`
	VideoID   uuid.UUID          `json:"video_id"`
	Platform  string             `json:"platform"`
	Item      string             `json:"item"`
	Done      bool               `json:"done"`
	DoneAt    pgtype.Timestamptz `json:"done_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type RenderArtifact struct {
	ID        uuid.UUID `json:"id"`
	VideoID   uuid.UUID `json:"video_id"`
	Path      string    `json:"path"`
	Sha256    string    `json:"sha256"`
	Bytes     int64     `json:"bytes"`
	DurationS float64   `json:"duration_s"`
	Warnings  []string  `json:"warnings"`
	CreatedAt time.Time `json:"created_at"`
}

type RssItem struct {
	Guid    string      `json:"guid"`
	VideoID pgtype.UUID `json:"video_id"`
	SeenAt  time.Time   `json:"seen_at"`
}

type Take struct {
	ID         uuid.UUID `json:"id"`
	VideoSlug  string    `json:"video_slug"`
	SegmentID  string    `json:"segment_id"`
	Kind       string    `json:"kind"`
	RelPath    string    `json:"rel_path"`
	SizeBytes  int64     `json:"size_bytes"`
	Sha256     string    `json:"sha256"`
	DurationMs int64     `json:"duration_ms"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type Video struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Title          string    `json:"title"`
	SourceUrl      string    `json:"source_url"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	OriginalScript []byte    `json:"original_script"`
}

type VideoArtifactParse struct {
	ID        uuid.UUID `json:"id"`
	VideoID   uuid.UUID `json:"video_id"`
	Artifact  string    `json:"artifact"`
	Valid     bool      `json:"valid"`
	Errors    []byte    `json:"errors"`
	CreatedAt time.Time `json:"created_at"`
}

type VideoStatusHistory struct {
	ID        uuid.UUID `json:"id"`
	VideoID   uuid.UUID `json:"video_id"`
	Status    string    `json:"status"`
	Reason    string    `json:"reason"`
	Actor     string    `json:"actor"`
	CreatedAt time.Time `json:"created_at"`
}
