// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RssItem struct {
	Guid    string      `json:"guid"`
	VideoID pgtype.UUID `json:"video_id"`
	SeenAt  time.Time   `json:"seen_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type Video struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Title          string    `json:"title"`
	SourceUrl      string    `json:"source_url"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	OriginalScript []byte    `json:"original_script"`
}

type VideoArtifactParse struct {
	ID        uuid.UUID `json:"id"`
	VideoID   uuid.UUID `json:"video_id"`
	Artifact  string    `json:"artifact"`
	Valid     bool      `json:"valid"`
	Errors    []byte    `json:"errors"`
	CreatedAt time.Time `json:"created_at"`
}

type VideoStatusHistory struct {
	ID        uuid.UUID `json:"id"`
	VideoID   uuid.UUID `json:"video_id"`
	Status    string    `json:"status"`
	Reason    string    `json:"reason"`
	Actor     string    `json:"actor"`
	CreatedAt time.Time `json:"created_at"`
}
