// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUserIfNotExists(ctx context.Context, arg CreateUserIfNotExistsParams) (int64, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVideo(ctx context.Context, id uuid.UUID) (Video, error)
	ListVideos(ctx context.Context) ([]Video, error)
}

var _ Querier = (*Queries)(nil)
