// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ClaimJob must stay a SINGLE statement: SELECT … FOR UPDATE SKIP LOCKED
	// inside the UPDATE subquery is what makes concurrent claims safe (D-02).
	ClaimJob(ctx context.Context, claimedBy pgtype.Text) (Job, error)
	CompleteJob(ctx context.Context, arg CompleteJobParams) (Job, error)
	CountChecklistItems(ctx context.Context, videoID uuid.UUID) (int64, error)
	CountRssItems(ctx context.Context) (int64, error)
	CountTakesForVideo(ctx context.Context, videoSlug string) (int64, error)
	CountUnpublishedItems(ctx context.Context, videoID uuid.UUID) (int64, error)
	CreateUserIfNotExists(ctx context.Context, arg CreateUserIfNotExistsParams) (int64, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteTakesBySegment(ctx context.Context, arg DeleteTakesBySegmentParams) error
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error)
	// FailJob increments attempts; below max_attempts the job returns to pending
	// with exponential backoff (2^attempts × 30 s), otherwise it settles failed.
	FailJob(ctx context.Context, arg FailJobParams) (Job, error)
	// Non-retryable failure settles the job as failed immediately.
	FailJobTerminal(ctx context.Context, arg FailJobTerminalParams) (Job, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetOriginalScript(ctx context.Context, id uuid.UUID) ([]byte, error)
	GetRenderArtifactByPath(ctx context.Context, arg GetRenderArtifactByPathParams) (RenderArtifact, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVideo(ctx context.Context, id uuid.UUID) (Video, error)
	GetVideoBySlug(ctx context.Context, slug string) (Video, error)
	HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) (Job, error)
	InsertArtifactParse(ctx context.Context, arg InsertArtifactParseParams) (VideoArtifactParse, error)
	InsertRssItem(ctx context.Context, arg InsertRssItemParams) (int64, error)
	InsertStatusChange(ctx context.Context, arg InsertStatusChangeParams) error
	ListJobsByVideo(ctx context.Context, videoID uuid.UUID) ([]Job, error)
	ListParsesByVideo(ctx context.Context, videoID uuid.UUID) ([]VideoArtifactParse, error)
	ListReleaseChecklist(ctx context.Context, videoID uuid.UUID) ([]ReleaseChecklist, error)
	ListRenderArtifacts(ctx context.Context, videoID uuid.UUID) ([]RenderArtifact, error)
	ListStatusHistoryByVideo(ctx context.Context, videoID uuid.UUID) ([]VideoStatusHistory, error)
	ListTakesByVideo(ctx context.Context, videoSlug string) ([]Take, error)
	ListVideos(ctx context.Context) ([]Video, error)
	// Cancel is cooperative: a pending job with cancel_requested is skipped by
	// the claim scan; a claimed job sees the flag via GetJob/Heartbeat.
	MarkCancelRequested(ctx context.Context, id uuid.UUID) (Job, error)
	// Release a claim when the follow-up transition fails (S5-02 note: never
	// leave a claimed job without an owner).
	ResetJobToPending(ctx context.Context, id uuid.UUID) error
	SetChecklistItemPublished(ctx context.Context, arg SetChecklistItemPublishedParams) (ReleaseChecklist, error)
	SetOriginalScript(ctx context.Context, arg SetOriginalScriptParams) (int64, error)
	SetRssItemVideo(ctx context.Context, arg SetRssItemVideoParams) error
	UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) (Job, error)
	UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error
	UpsertChecklistItem(ctx context.Context, arg UpsertChecklistItemParams) error
	UpsertRenderArtifact(ctx context.Context, arg UpsertRenderArtifactParams) (RenderArtifact, error)
	UpsertTake(ctx context.Context, arg UpsertTakeParams) (Take, error)
}

var _ Querier = (*Queries)(nil)
