// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: release_checklist.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countReleaseChecklistOpen = `-- name: CountReleaseChecklistOpen :one
SELECT count(*) AS open FROM release_checklist
WHERE video_id = $1 AND done = false
`

func (q *Queries) CountReleaseChecklistOpen(ctx context.Context, videoID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReleaseChecklistOpen, videoID)
	var open int64
	err := row.Scan(&open)
	return open, err
}

const listReleaseChecklist = `-- name: ListReleaseChecklist :many
SELECT id, video_id, platform, item, done, done_at, created_at FROM release_checklist WHERE video_id = $1 ORDER BY created_at
`

func (q *Queries) ListReleaseChecklist(ctx context.Context, videoID uuid.UUID) ([]ReleaseChecklist, error) {
	rows, err := q.db.Query(ctx, listReleaseChecklist, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseChecklist
	for rows.Next() {
		var i ReleaseChecklist
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Platform,
			&i.Item,
			&i.Done,
			&i.DoneAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedReleaseChecklistItem = `-- name: SeedReleaseChecklistItem :exec
INSERT INTO release_checklist (video_id, platform)
VALUES ($1, $2)
ON CONFLICT (video_id, platform) DO NOTHING
`

type SeedReleaseChecklistItemParams struct {
	VideoID  uuid.UUID `json:"video_id"`
	Platform string    `json:"platform"`
}

func (q *Queries) SeedReleaseChecklistItem(ctx context.Context, arg SeedReleaseChecklistItemParams) error {
	_, err := q.db.Exec(ctx, seedReleaseChecklistItem, arg.VideoID, arg.Platform)
	return err
}

const setReleaseChecklistDone = `-- name: SetReleaseChecklistDone :one
UPDATE release_checklist SET done = true, done_at = now()
WHERE video_id = $1 AND platform = $2
RETURNING id, video_id, platform, item, done, done_at, created_at
`

type SetReleaseChecklistDoneParams struct {
	VideoID  uuid.UUID `json:"video_id"`
	Platform string    `json:"platform"`
}

func (q *Queries) SetReleaseChecklistDone(ctx context.Context, arg SetReleaseChecklistDoneParams) (ReleaseChecklist, error) {
	row := q.db.QueryRow(ctx, setReleaseChecklistDone, arg.VideoID, arg.Platform)
	var i ReleaseChecklist
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Platform,
		&i.Item,
		&i.Done,
		&i.DoneAt,
		&i.CreatedAt,
	)
	return i, err
}
