// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: release_checklist.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countChecklistItems = `-- name: CountChecklistItems :one
SELECT count(*) AS total FROM release_checklist WHERE video_id = $1
`

func (q *Queries) CountChecklistItems(ctx context.Context, videoID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChecklistItems, videoID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUnpublishedItems = `-- name: CountUnpublishedItems :one
SELECT count(*) AS open FROM release_checklist
WHERE video_id = $1 AND published = false
`

func (q *Queries) CountUnpublishedItems(ctx context.Context, videoID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnpublishedItems, videoID)
	var open int64
	err := row.Scan(&open)
	return open, err
}

const listReleaseChecklist = `-- name: ListReleaseChecklist :many
SELECT id, video_id, item_key, label, download_path, published, published_at, created_at FROM release_checklist WHERE video_id = $1 ORDER BY created_at
`

func (q *Queries) ListReleaseChecklist(ctx context.Context, videoID uuid.UUID) ([]ReleaseChecklist, error) {
	rows, err := q.db.Query(ctx, listReleaseChecklist, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseChecklist
	for rows.Next() {
		var i ReleaseChecklist
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ItemKey,
			&i.Label,
			&i.DownloadPath,
			&i.Published,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChecklistItemPublished = `-- name: SetChecklistItemPublished :one
UPDATE release_checklist SET published = $3, published_at = CASE WHEN $3 THEN now() ELSE NULL END
WHERE video_id = $1 AND item_key = $2
RETURNING id, video_id, item_key, label, download_path, published, published_at, created_at
`

type SetChecklistItemPublishedParams struct {
	VideoID   uuid.UUID `json:"video_id"`
	ItemKey   string    `json:"item_key"`
	Published bool      `json:"published"`
}

func (q *Queries) SetChecklistItemPublished(ctx context.Context, arg SetChecklistItemPublishedParams) (ReleaseChecklist, error) {
	row := q.db.QueryRow(ctx, setChecklistItemPublished, arg.VideoID, arg.ItemKey, arg.Published)
	var i ReleaseChecklist
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ItemKey,
		&i.Label,
		&i.DownloadPath,
		&i.Published,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertChecklistItem = `-- name: UpsertChecklistItem :exec
INSERT INTO release_checklist (video_id, item_key, label, download_path)
VALUES ($1, $2, $3, $4)
ON CONFLICT (video_id, item_key) DO UPDATE SET
  label = excluded.label,
  download_path = excluded.download_path
`

type UpsertChecklistItemParams struct {
	VideoID      uuid.UUID `json:"video_id"`
	ItemKey      string    `json:"item_key"`
	Label        string    `json:"label"`
	DownloadPath string    `json:"download_path"`
}

func (q *Queries) UpsertChecklistItem(ctx context.Context, arg UpsertChecklistItemParams) error {
	_, err := q.db.Exec(ctx, upsertChecklistItem,
		arg.VideoID,
		arg.ItemKey,
		arg.Label,
		arg.DownloadPath,
	)
	return err
}
