// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: render_artifacts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getRenderArtifactByPath = `-- name: GetRenderArtifactByPath :one
SELECT id, video_id, path, sha256, bytes, duration_s, warnings, created_at FROM render_artifacts WHERE video_id = $1 AND path = $2
`

type GetRenderArtifactByPathParams struct {
	VideoID uuid.UUID `json:"video_id"`
	Path    string    `json:"path"`
}

func (q *Queries) GetRenderArtifactByPath(ctx context.Context, arg GetRenderArtifactByPathParams) (RenderArtifact, error) {
	row := q.db.QueryRow(ctx, getRenderArtifactByPath, arg.VideoID, arg.Path)
	var i RenderArtifact
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Path,
		&i.Sha256,
		&i.Bytes,
		&i.DurationS,
		&i.Warnings,
		&i.CreatedAt,
	)
	return i, err
}

const listRenderArtifacts = `-- name: ListRenderArtifacts :many
SELECT id, video_id, path, sha256, bytes, duration_s, warnings, created_at FROM render_artifacts WHERE video_id = $1 ORDER BY created_at
`

func (q *Queries) ListRenderArtifacts(ctx context.Context, videoID uuid.UUID) ([]RenderArtifact, error) {
	rows, err := q.db.Query(ctx, listRenderArtifacts, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenderArtifact
	for rows.Next() {
		var i RenderArtifact
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Path,
			&i.Sha256,
			&i.Bytes,
			&i.DurationS,
			&i.Warnings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRenderArtifact = `-- name: UpsertRenderArtifact :one
INSERT INTO render_artifacts (video_id, path, sha256, bytes, duration_s, warnings)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (video_id, path) DO UPDATE SET
  sha256 = excluded.sha256,
  bytes = excluded.bytes,
  duration_s = excluded.duration_s,
  warnings = excluded.warnings,
  created_at = now()
RETURNING id, video_id, path, sha256, bytes, duration_s, warnings, created_at
`

type UpsertRenderArtifactParams struct {
	VideoID   uuid.UUID `json:"video_id"`
	Path      string    `json:"path"`
	Sha256    string    `json:"sha256"`
	Bytes     int64     `json:"bytes"`
	DurationS float64   `json:"duration_s"`
	Warnings  []string  `json:"warnings"`
}

func (q *Queries) UpsertRenderArtifact(ctx context.Context, arg UpsertRenderArtifactParams) (RenderArtifact, error) {
	row := q.db.QueryRow(ctx, upsertRenderArtifact,
		arg.VideoID,
		arg.Path,
		arg.Sha256,
		arg.Bytes,
		arg.DurationS,
		arg.Warnings,
	)
	var i RenderArtifact
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Path,
		&i.Sha256,
		&i.Bytes,
		&i.DurationS,
		&i.Warnings,
		&i.CreatedAt,
	)
	return i, err
}
