// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: takes.sql

package sqlc

import (
	"context"
)

const countTakesForVideo = `-- name: CountTakesForVideo :one
SELECT count(*) FROM takes WHERE video_slug = $1
`

func (q *Queries) CountTakesForVideo(ctx context.Context, videoSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, countTakesForVideo, videoSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listTakesByVideo = `-- name: ListTakesByVideo :many
SELECT id, video_slug, segment_id, kind, rel_path, size_bytes, sha256, duration_ms, created_at FROM takes WHERE video_slug = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTakesByVideo(ctx context.Context, videoSlug string) ([]Take, error) {
	rows, err := q.db.Query(ctx, listTakesByVideo, videoSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Take
	for rows.Next() {
		var i Take
		if err := rows.Scan(
			&i.ID,
			&i.VideoSlug,
			&i.SegmentID,
			&i.Kind,
			&i.RelPath,
			&i.SizeBytes,
			&i.Sha256,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTake = `-- name: UpsertTake :one
INSERT INTO takes (video_slug, segment_id, kind, rel_path, size_bytes, sha256, duration_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (video_slug, segment_id, kind) DO UPDATE SET
    rel_path = EXCLUDED.rel_path,
    size_bytes = EXCLUDED.size_bytes,
    sha256 = EXCLUDED.sha256,
    duration_ms = EXCLUDED.duration_ms,
    created_at = now()
RETURNING id, video_slug, segment_id, kind, rel_path, size_bytes, sha256, duration_ms, created_at
`

type UpsertTakeParams struct {
	VideoSlug  string `json:"video_slug"`
	SegmentID  string `json:"segment_id"`
	Kind       string `json:"kind"`
	RelPath    string `json:"rel_path"`
	SizeBytes  int64  `json:"size_bytes"`
	Sha256     string `json:"sha256"`
	DurationMs int64  `json:"duration_ms"`
}

func (q *Queries) UpsertTake(ctx context.Context, arg UpsertTakeParams) (Take, error) {
	row := q.db.QueryRow(ctx, upsertTake,
		arg.VideoSlug,
		arg.SegmentID,
		arg.Kind,
		arg.RelPath,
		arg.SizeBytes,
		arg.Sha256,
		arg.DurationMs,
	)
	var i Take
	err := row.Scan(
		&i.ID,
		&i.VideoSlug,
		&i.SegmentID,
		&i.Kind,
		&i.RelPath,
		&i.SizeBytes,
		&i.Sha256,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}
