// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRssItems = `-- name: CountRssItems :one
SELECT count(*) FROM rss_items
`

func (q *Queries) CountRssItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRssItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (slug, title, source_url)
VALUES ($1, $2, $3)
RETURNING id, slug, title, source_url, status, created_at, updated_at
`

type CreateVideoParams struct {
	Slug      string `json:"slug"`
	Title     string `json:"title"`
	SourceUrl string `json:"source_url"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo, arg.Slug, arg.Title, arg.SourceUrl)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.SourceUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, slug, title, source_url, status, created_at, updated_at FROM videos WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.SourceUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRssItem = `-- name: InsertRssItem :execrows
INSERT INTO rss_items (guid, video_id)
VALUES ($1, $2)
ON CONFLICT (guid) DO NOTHING
`

type InsertRssItemParams struct {
	Guid    string      `json:"guid"`
	VideoID pgtype.UUID `json:"video_id"`
}

func (q *Queries) InsertRssItem(ctx context.Context, arg InsertRssItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRssItem, arg.Guid, arg.VideoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listVideos = `-- name: ListVideos :many
SELECT id, slug, title, source_url, status, created_at, updated_at FROM videos ORDER BY created_at DESC LIMIT 200
`

func (q *Queries) ListVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.SourceUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRssItemVideo = `-- name: SetRssItemVideo :exec
UPDATE rss_items SET video_id = $2 WHERE guid = $1
`

type SetRssItemVideoParams struct {
	Guid    string      `json:"guid"`
	VideoID pgtype.UUID `json:"video_id"`
}

func (q *Queries) SetRssItemVideo(ctx context.Context, arg SetRssItemVideoParams) error {
	_, err := q.db.Exec(ctx, setRssItemVideo, arg.Guid, arg.VideoID)
	return err
}
