// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRssItems = `-- name: CountRssItems :one
SELECT count(*) FROM rss_items
`

func (q *Queries) CountRssItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRssItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (slug, title, source_url)
VALUES ($1, $2, $3)
RETURNING id, slug, title, source_url, status, created_at, updated_at, original_script
`

type CreateVideoParams struct {
	Slug      string `json:"slug"`
	Title     string `json:"title"`
	SourceUrl string `json:"source_url"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo, arg.Slug, arg.Title, arg.SourceUrl)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.SourceUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalScript,
	)
	return i, err
}

const getOriginalScript = `-- name: GetOriginalScript :one
SELECT original_script FROM videos WHERE id = $1
`

func (q *Queries) GetOriginalScript(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOriginalScript, id)
	var original_script []byte
	err := row.Scan(&original_script)
	return original_script, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, slug, title, source_url, status, created_at, updated_at, original_script FROM videos WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.SourceUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalScript,
	)
	return i, err
}

const getVideoBySlug = `-- name: GetVideoBySlug :one
SELECT id, slug, title, source_url, status, created_at, updated_at, original_script FROM videos WHERE slug = $1
`

func (q *Queries) GetVideoBySlug(ctx context.Context, slug string) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoBySlug, slug)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.SourceUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalScript,
	)
	return i, err
}

const insertArtifactParse = `-- name: InsertArtifactParse :one
INSERT INTO video_artifact_parses (video_id, artifact, valid, errors)
VALUES ($1, $2, $3, $4)
RETURNING id, video_id, artifact, valid, errors, created_at
`

type InsertArtifactParseParams struct {
	VideoID  uuid.UUID `json:"video_id"`
	Artifact string    `json:"artifact"`
	Valid    bool      `json:"valid"`
	Errors   []byte    `json:"errors"`
}

func (q *Queries) InsertArtifactParse(ctx context.Context, arg InsertArtifactParseParams) (VideoArtifactParse, error) {
	row := q.db.QueryRow(ctx, insertArtifactParse,
		arg.VideoID,
		arg.Artifact,
		arg.Valid,
		arg.Errors,
	)
	var i VideoArtifactParse
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Artifact,
		&i.Valid,
		&i.Errors,
		&i.CreatedAt,
	)
	return i, err
}

const insertRssItem = `-- name: InsertRssItem :execrows
INSERT INTO rss_items (guid, video_id)
VALUES ($1, $2)
ON CONFLICT (guid) DO NOTHING
`

type InsertRssItemParams struct {
	Guid    string      `json:"guid"`
	VideoID pgtype.UUID `json:"video_id"`
}

func (q *Queries) InsertRssItem(ctx context.Context, arg InsertRssItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRssItem, arg.Guid, arg.VideoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertStatusChange = `-- name: InsertStatusChange :exec
INSERT INTO video_status_history (video_id, status, reason, actor)
VALUES ($1, $2, $3, $4)
`

type InsertStatusChangeParams struct {
	VideoID uuid.UUID `json:"video_id"`
	Status  string    `json:"status"`
	Reason  string    `json:"reason"`
	Actor   string    `json:"actor"`
}

func (q *Queries) InsertStatusChange(ctx context.Context, arg InsertStatusChangeParams) error {
	_, err := q.db.Exec(ctx, insertStatusChange,
		arg.VideoID,
		arg.Status,
		arg.Reason,
		arg.Actor,
	)
	return err
}

const listParsesByVideo = `-- name: ListParsesByVideo :many
SELECT id, video_id, artifact, valid, errors, created_at FROM video_artifact_parses WHERE video_id = $1 ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListParsesByVideo(ctx context.Context, videoID uuid.UUID) ([]VideoArtifactParse, error) {
	rows, err := q.db.Query(ctx, listParsesByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoArtifactParse
	for rows.Next() {
		var i VideoArtifactParse
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Artifact,
			&i.Valid,
			&i.Errors,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusHistoryByVideo = `-- name: ListStatusHistoryByVideo :many
SELECT id, video_id, status, reason, actor, created_at FROM video_status_history WHERE video_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListStatusHistoryByVideo(ctx context.Context, videoID uuid.UUID) ([]VideoStatusHistory, error) {
	rows, err := q.db.Query(ctx, listStatusHistoryByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoStatusHistory
	for rows.Next() {
		var i VideoStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Status,
			&i.Reason,
			&i.Actor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideos = `-- name: ListVideos :many
SELECT id, slug, title, source_url, status, created_at, updated_at, original_script FROM videos ORDER BY created_at DESC LIMIT 200
`

func (q *Queries) ListVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.SourceUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalScript,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOriginalScript = `-- name: SetOriginalScript :execrows
UPDATE videos SET original_script = $2 WHERE id = $1 AND original_script IS NULL
`

type SetOriginalScriptParams struct {
	ID             uuid.UUID `json:"id"`
	OriginalScript []byte    `json:"original_script"`
}

func (q *Queries) SetOriginalScript(ctx context.Context, arg SetOriginalScriptParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOriginalScript, arg.ID, arg.OriginalScript)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRssItemVideo = `-- name: SetRssItemVideo :exec
UPDATE rss_items SET video_id = $2 WHERE guid = $1
`

type SetRssItemVideoParams struct {
	Guid    string      `json:"guid"`
	VideoID pgtype.UUID `json:"video_id"`
}

func (q *Queries) SetRssItemVideo(ctx context.Context, arg SetRssItemVideoParams) error {
	_, err := q.db.Exec(ctx, setRssItemVideo, arg.Guid, arg.VideoID)
	return err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :exec
UPDATE videos SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateVideoStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error {
	_, err := q.db.Exec(ctx, updateVideoStatus, arg.ID, arg.Status)
	return err
}
